//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookit.Biz.FreeBusyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FreeBusyService.IFreeBusyService")]
    public interface IFreeBusyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFreeBusyService/GetFreeBusy", ReplyAction="http://tempuri.org/IFreeBusyService/GetFreeBusyResponse")]
        string GetFreeBusy(string email, System.DateTime stime, int duration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFreeBusyService/IsFree", ReplyAction="http://tempuri.org/IFreeBusyService/IsFreeResponse")]
        bool IsFree(string email, System.DateTime stime, int duration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFreeBusyService/IsFreeForNext", ReplyAction="http://tempuri.org/IFreeBusyService/IsFreeForNextResponse")]
        System.Collections.Generic.KeyValuePair<System.DateTime, int> IsFreeForNext(string email, int minutes, System.DateTime stime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFreeBusyServiceChannel : Bookit.Biz.FreeBusyService.IFreeBusyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FreeBusyServiceClient : System.ServiceModel.ClientBase<Bookit.Biz.FreeBusyService.IFreeBusyService>, Bookit.Biz.FreeBusyService.IFreeBusyService {
        
        public FreeBusyServiceClient() {
        }
        
        public FreeBusyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FreeBusyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FreeBusyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FreeBusyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetFreeBusy(string email, System.DateTime stime, int duration) {
            return base.Channel.GetFreeBusy(email, stime, duration);
        }
        
        public bool IsFree(string email, System.DateTime stime, int duration) {
            return base.Channel.IsFree(email, stime, duration);
        }
        
        public System.Collections.Generic.KeyValuePair<System.DateTime, int> IsFreeForNext(string email, int minutes, System.DateTime stime) {
            return base.Channel.IsFreeForNext(email, minutes, stime);
        }
    }
}
